# Generated by Django 5.1.5 on 2025-01-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('interviewer', 'Interviewer'), ('manager', 'HRManager')], default='candidate', max_length=15),
        ),
    ]
